spring.datasource.url=jdbc:mysql://localhost:3306/fitnesslion
spring.datasource.username=root
spring.datasource.password=Alvinseeco30

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081